### ISSUE TITLE
Odoo 15

### ISSUE THREAD

**Issue by Galoperd** [thespino/odoogpt#42] opened 2023-04-07 20:27 UTC
Hi, I forked your project and trying to work in a Odoo 15 version. When installing the module it gives AttributeError: module 'odoo.fields' has no attribute 'Json' related to OdoogptOpenaiModel.py file, permission = fields.Json(). As far as I read, json fields are available since Odoo 14 so I am not sure what is happening. Your comment is appreciatted.

**Comment by thespino** [comment] 2023-04-07 21:04
Hi Galoperd, 
Thank you for contributing! 
I don't have my PC here right now, so I'll better check tomorrow, but I have checked both Odoo 16 and Odoo 15 code in fields.py, and there's no Json field in v15.

If you try searching `class Json` here https://github.com/odoo/odoo/blob/16.0/odoo/fields.py you can find it. But if you search it here https://github.com/odoo/odoo/blob/15.0/odoo/fields.py it's not present.  So I think is something new in v16.

I think that we could bypass Json field, as a simple text field would be enough, but  maybe we need to convert the field into Json format before reading it somewhere... 

Tomorrow I'll do a better check (i'm in Italy, i don't know which is your timezones).

**Comment by thespino** [comment] 2023-04-08 10:32
Ok, i can confirm that Json fields are available since odoo 16.0:  https://mergebot.odoo.com/odoo/odoo/pull/101701 
That's not merged into previous versions. 

I'm quite sure we can keep it as a text field; if you look at `_compute_permission_string` function, you can see it only gets the json and converts it into a string with indentation (which is only used for display purposes). 

So i think we can do something like: 
```
    permission = fields.Text(                # <---
        string='OpenAI permission',
        required=False,
        default=False,
    )

...

    def _compute_permission_string(self):
        for openai_model in self:
            openai_model.permission_string = json.dumps(
                jsom.dump(self.permission or '{}'),        # <---
                indent=4
            )


```

**Comment by Galoperd** [comment] 2023-04-09 07:28
Many thanks for the feedback, now it is installing without errors on Odoo 15 with your proposed code. Note: your code had two typos json.dumps(self.permission or '{}'). However /ai prompt does not work. OdooBot is answering as for usual OdooBot, not as OpenAi. My API key working correctly in VSCode. Odoo log (debug) shows no error. Same issue with openai-0.26.1 or openai-0.27.0. Your guide is appreciatted.

**Comment by thespino** [comment] 2023-04-09 09:47
I think there's a problem with assets... 

Look at the manifest: 
https://github.com/thespino/odoogpt/blob/2eca538030cc5543d8d7fdf8b66aee86ef9c6ce5/odoogpt/__manifest__.py#L41-L43 
here we import the asset which defines the `/ai` command and the function to be executed into mail_channel.

Looking at Odoo 15 code in crm_livechat module for example, I can see there's a difference in assets names: 
https://github.com/odoo/odoo/blob/9055292570ce365898cf59e3749f99b62b70a636/addons/crm_livechat/__manifest__.py#L19-L24

It looks like Odoo 15 makes some differences between website and backend chat, so I think that we have to split our asset `mail.assets_messaging` in both `mail.assets_discuss_public` and `web.assets_backend`, like so: 

```
    'assets': {
        'mail.assets_discuss_public': [
            'odoogpt/static/src/models/*.js',
        ],
        'mail.assets_backend': [
            'odoogpt/static/src/models/*.js',
        ],
    },

```


And looking at the js script itself, it looks like it's quite different: https://github.com/odoo/odoo/blob/9055292570ce365898cf59e3749f99b62b70a636/addons/crm_livechat/static/src/models/messaging_initializer/messaging_initializer.js 
I.e.: 
- Function `registerInstancePatchModel` instead of `registerPatch`
- Different structure of the function itself

**Comment by Galoperd** [comment] 2023-04-09 10:46
Hi, will definetively check ! one question: is the /ai prompt usable within all Odoo users chat or just with Odooboot chat ?

**Comment by thespino** [comment] 2023-04-09 10:49
It should work in any chat, since it's a command. OdooBot should be able to respond also if it isn't in the channel

**Comment by Galoperd** [comment] 2023-04-09 19:23
Hi, it is now working in Odoo 15. About "Chat method", when setting chat completion it gives the following error: 
_OdooGPT: We're sorry, ChatCompletion is not available in your system. Check that openai python module version is >= 0.27.0 to use this functionality. Installed version: 0.26.1 See https://github.com/openai/openai-python/releases/tag/v0.27.0_
Also the OpenAI Models list does not appear or refresh. When moving to openai-0.27.1, then chat completion works and OpenAI Models list appears and refresh. Is this the same for you in Odoo 16 ?

**Comment by Galoperd** [comment] 2023-04-09 19:33
Sorry I was too early to say it is working. When moving to openai-0.27.1, then Odoobot does not respond as Chatgpt with ai/ prompt. As for now it seems to work with odoo 15 + openai-0.26.1 + completion, but then no list for OpenAI Models and no chat completion. Will continue testing. Your guide is much appreciatted.

**Comment by thespino** [comment] 2023-04-09 21:28
The message you get when enabling chat completion is correct, it's a check to prevent errors, because chat completion is implemented since openai 0.27.0. 

If you see empty model list, i recommend you clicking `Settings → OdooGPT → Refresh OpenAI Models` and then open the list under `Settings → OdooGPT → OpenAI Models`. 
The refresh menu item will read models from openai api and add them to the table. 
Ref. https://odoogpt.thespino.dev/1.0.0/docs/advanced-usage/openai-models/ 


If any error occurs during the refresh method, it will be displayed as UserError in the page.
I recommend looking at the refresh_from_api function on the odoogpt mixin: https://github.com/thespino/odoogpt/blob/2eca538030cc5543d8d7fdf8b66aee86ef9c6ce5/odoogpt/models/odoogpt_openai_mixin.py#L47

**Comment by Galoperd** [comment] 2023-04-10 10:43
New test environment: fresh Odoo 15 database + openai-0.26.1 + first odoogpt install + no odoogpt standard settings modification => when writting the API key it appears the message _OdooGPT: We're sorry, ChatCompletion is not available in your system. Check that openai python module version is >= 0.27.0 to use this functionality. Installed version: 0.26.1 See https://github.com/openai/openai-python/releases/tag/v0.27.0_ Test result: as far as I see API key cannot be stored. Appreciate your comments.

**Comment by thespino** [comment] 2023-04-10 12:36
I haven't updated documentation about it so far, but requirements are: 
- `openai >= 0.27.0` to use chat-completion or completion 
- any version < 0.27.0 to use **only completion** 

So that's fine you get this error with openai-0.26.1. 
You can: 
- install openai >= 0.27.0 an keep using chat completion 
- keep openai 0.26.* and swith to completion. 

For this there's a selector under "settings > odoogpt" in "OdooGPT Chat Customization" section where you can choose between completion or chat-completion.  

If requirements are not satisfied, the warning message prevents you to save settings. It's done to prevent errors when chatting, which are more difficult to debug. 

If something is not working during chat (i.e. error messages, or odoobot responding even with /ai command), i recommend debugging the **execute_command_ai** function:  https://github.com/thespino/odoogpt/blob/2eca538030cc5543d8d7fdf8b66aee86ef9c6ce5/odoogpt/models/mail_channel.py#L12 

I don't have so much time today, so maybe later or tomorrow i think i'll prepare an odoo 15 installation locally, so i can debug on your branch and see what's going on. 

Thanks for the interest! Keep me updated

**Comment by thespino** [comment] 2023-04-13 19:48
Hi Galoperd, 
Thanks for the patience. 

I tested your fork into: 
- Odoo 15 + openai 0.27.4 + completion 
- Odoo 15 + openai 0.27.4 + chat-completion 

and everything is working fine! 

BUT, when testing with 
- Odoo 15 + openai 0.26.3 + completion 

**I'm not able to save setting due to the message about chat completions not being available in the system.**

**And it's a stupid error I made!**
https://github.com/thespino/odoogpt/blob/2eca538030cc5543d8d7fdf8b66aee86ef9c6ce5/odoogpt/models/res_company.py#L14 
should be
```python
if any(company.odoogpt_chat_method == 'chat-completion' for company in self) and not hasattr(openai, 'ChatCompletion'):
```

Furthermore, you should use model `gpt-3.5-turbo` instead of `text-davinci-003` when using chat completion; it depends on the account/subscription, but generally davinci is not available with chat completion. 

So i'm fixing this on 16.0 right now, i'm gonna tell when i'm done so you can update your fork and get the chages.

**Comment by thespino** [comment] 2023-04-13 20:01
Ok, 
On branch 16.0  https://github.com/thespino/odoogpt/tree/16.0  there's the fix. 
Please update your fork so you have the change. 

Let me know if you need more help! 

Thank you

**Comment by thespino** [comment] 2023-04-22 11:29
Hi @Galoperd ! 
Any news on it?

**Comment by Galoperd** [comment] 2023-04-23 11:24
Hi @thespino sorry for the delay, quite busy here... I updated my 15.0 fork and everything works now. I am not very experienced with git, feel free to update your repository. Thanks for everything ;)

**Comment by thespino** [comment] 2023-04-23 19:43
That's wonderful! 
I created the 15.0 branch on the main repository https://github.com/thespino/odoogpt/tree/15.0
when you're ready you can create a pull request to merge changes. 

Thank you!

**Comment by thespino** [comment] 2023-04-27 17:07
Merged! See https://github.com/thespino/odoogpt/pull/43

**Closed as completed by thespino** 2023-04-27 17:07 UTC
Labels: help wanted
